export const sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['italy'], 
        stars: 4.5, 
        imageUrl: 'food-1.jpg', 
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'meat ball', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['persia','middle east','china'], 
        stars: 5, 
        imageUrl: 'food-2.jpg', 
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'meat ball', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['persia','middle east','china'], 
        stars: 2, 
        imageUrl: 'food-3.jpg', 
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '4',
        name: 'meat ball', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['persia','middle east','china'], 
        stars: 3, 
        imageUrl: 'food-4.jpg', 
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '5',
        name: 'meat ball', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['persia','middle east','china'], 
        stars: 3, 
        imageUrl: 'food-5.jpg', 
        tags: ['FastFood', 'Lunch'],
    },
    {
        id: '6',
        name: 'meat ball', 
        cookTime: '10-20', 
        price: 10, 
        favorite: false, 
        origins: ['persia','middle east','china'], 
        stars: 3, 
        imageUrl: 'food-6.jpg', 
        tags: ['FastFood', 'Lunch'],
    },


]